### ISSUE TITLE
어제 만들었던 연동과정에 질문이 있습니다.

### ISSUE THREAD

**Issue by lkc263** [lkc263/gd_backend#3]
어제 만들었던 연동과정에 질문이 있습니다.

1) mysql workbench에서 EER 다이어그램을 migrate 하여 models, serializers, views, urls 을 생성합니다.
- settings databases에서는 mysql로 설정을 바꿔줍니다.
2) 이제 heroku 스키마를 추가합니다.
- 여기 문제점이 Forward engineer이 되지 않아, 
- settings databases에서 mysql -> sqlite로 바꿉니다.
- setting_heroku를 생성합니다.
- Procfile을 통해 서버를 실행시키기 위해 gdproject.wsgi.py에서도 runserver with settings -> runserver with settings_heroku로 바꾸어줍니다.
- python manage.py migrate --settings=gdproject.settings_heroku을 하여 workbench heroku 스키마, Tables에 table들이 추가가 됩니다.

여기서 이해가 안되는 부분이 있습니다.
1)에서 workbench를 이용하여 생성된 models, serializers, views, urls 등이 sqlite에 지정됩니다.
(heroku 도입되기 전까지)
2) 이제 sqlite가 아닌, heroku_database, cleardb에 저장하기 위해 settings_heroku를 생성하여
Procfile -> gdproject.wsgi -> runserver with settings_heroku를 통해
지정한 DB가 sqlite에서 heroku, cleardb로 바뀐걸까요??

**Comment by aciddust** [comment]
>1)에서 workbench를 이용하여 생성된 models, serializers, views, urls 등이 sqlite에 지정됩니다.
(heroku 도입되기 전까지)

음. 그전엔 `settings.py`에서 데이터베이스 설정이 로컬에 있는 sqlite를 바라보게 되어있죠?
설정에 따라 바라보는 DB가 다른거에요.
Heroku를 사용하던 안하던 바라보고있는 DB는 설정에 따라 달라지죠 ㅎㅎ

>2) 이제 sqlite가 아닌, heroku_database, cleardb에 저장하기 위해 settings_heroku를 생성하여
Procfile -> gdproject.wsgi -> runserver with settings_heroku를 통해
지정한 DB가 sqlite에서 heroku, cleardb로 바뀐걸까요??

새로 작성한 `settings_heroku.py`의 DB설정은 Heroku, ClearDB를 바라보고있지요?
Heroku에서 Procfile에 작성된 스크립트를 기반으로 서버를 실행시켜주는데요
작성된 내용대로라면 `wsgi.py`를 통해 서버를 실행하고있지요?
`wsgi.py`를 타고 들어오면 서버를 구동하는 커맨드가 작성되어있죠?
배포환경에서는 ClearDB를 바라보고싶으니 설정파일 옵션에 settings_heroku 를 넣어서 실행시켜주고있죠?

ㅎㅎ

**Comment by lkc263** [comment]
아! 그렇군요ㅎㅎ
